jobs:
 - name: aarch64_u16nodall
   type: runSh
   runtime:
     - custom__aarch64__Ubuntu_16_04
   steps:
     - TASK:
         runtime:
           options:
             imageName: "drydock/aarch64_u16nodall"
             imageTag: master
         script:
         - grunt --version
         - mocha --versio
         - vows --version
         - casperjs --version
         - bower --version
         - nodejs --version
         - npm --version
