jobs:
 - name: aarch64_u16nodall
   type: runSh
   steps:
     - TASK:
         runtime:
           options:
             imageName: "drydock/aarch64_u16nodall"
             imageTag: master
         script:
         - grunt --version
         - mocha --version
         - vows --version
         - bower --version
         - nvm list
         - npm --version
         - echo "hi"
        
